from slmsuite.holography.algorithms._header import *
from slmsuite.holography.algorithms._hologram import Hologram
from slmsuite.misc.xp import as_numpy, get_array_module, is_gpu_array


# Transparent cache of the ``"ij"`` -> ``"knm"`` transformation, keyed on
# everything it depends on: the hologram shape, the Fourier calibration
# contents, the SLM pitch/shape, and the ROI origin. All are fixed across the
# repeated calls made by set_target() and measure(), which would otherwise
# redo the host-side composition and its upload every time. Keyed on
# calibration *contents* rather than identity, because `fourier_affine` builds
# a fresh object on every access; that also means recalibrating invalidates
# itself. Mirrors the ``_ZERNIKE_BASIS_CACHE`` idiom in
# `toolbox.phase._zernike`.
_IJCAM_TO_KNMSLM_CACHE = LRUCache(8)


def clear_ijcam_to_knmslm_cache():
    """
    Empty the transparent transformation cache used by
    :meth:`~slmsuite.holography.algorithms.FeedbackHologram.ijcam_to_knmslm`.
    The cache is keyed on the *contents* of the Fourier calibration, so
    recalibrating does not require this call; it exists mainly so tests can
    start from a known state.
    """
    _IJCAM_TO_KNMSLM_CACHE.clear()


class FeedbackHologram(Hologram):
    """
    Experimental holography aided by camera feedback.
    Contains mechanisms for hologram positioning and camera feedback aided by a
    :class:`~slmsuite.hardware.cameraslms.FourierSLM`.

    Attributes
    ----------
    cameraslm : slmsuite.hardware.cameraslms.FourierSLM OR None
        A hologram with experimental feedback needs access to an SLM and camera.
        If ``None``, no feedback is applied (mostly defaults to :class:`Hologram`).
    _cam_points : numpy.ndarray
        Array containing points corresponding to the corners of the camera in the SLM's
        k-space. At the moment, this is only used for plotting.
        First point is repeated at the end.
    target_ij : array_like OR None
        Amplitude target in the ``"ij"`` (camera) basis. Of same ``shape`` as
        the camera in :attr:`cameraslm`.  Counterpart to :attr:`target` which
        is in the ``"knm"`` (computational k-space) basis. If
        :attr:`target_ij_roi` is set, this is instead a *sub-image* of the
        camera frame.
    target_ij_roi : (int, int) OR None
        The ``(y, x)`` camera pixel that ``target_ij[0, 0]`` corresponds to,
        when the target was supplied as a sub-image rather than a full camera
        frame. Everything outside the sub-image is undefined. ``None`` when
        :attr:`target_ij` covers the full frame.
    img_ij, img_knm
        Cached **amplitude** feedback image in the
        ``"ij"`` (raw camera) basis or
        ``"knm"`` (transformed to computational k-space) basis.
        Measured with :meth:`.measure()`.
    """

    # Camera feedback adds the experimental source. See Hologram._feedback_supported.
    _feedback_supported = ("computational", "experimental")

    def __init__(
            self,
            shape,
            target_ij=None,
            cameraslm=None,
            null_region=None,
            null_region_radius_frac=None,
            target_ij_roi=None,
            **kwargs
        ):
        """
        Initializes a hologram with camera feedback.

        Parameters
        ----------
        shape : (int, int)
            Computational shape of the SLM in :mod:`numpy` `(h, w)` form. See :meth:`.Hologram.__init__()`.
        target_ij : array_like OR None
            See :attr:`target_ij`.
            Is ``None`` only if the :attr:`target` will be generated by other means
            (used by subclass :class:`SpotHologram`). This should not generally be used.

            Note
            ~~~~
            There is not currently a way to request a target in the ``"knm"`` basis and
            use the camera for feedback. In particular, the analog ``knmslm_to_ijcam``
            for :meth:`ijcam_to_knmslm()` is not written, but is definitely possible.
        cameraslm : slmsuite.hardware.cameraslms.FourierSLM OR slmsuite.hardware.slms.SLM OR None
            Provides access to experimental feedback.
            If an :class:`~slmsuite.hardware.slms.slm.SLM` is passed, the attribute is set to ``None``,
            but the information contained in the SLM is passed to the superclass :class:`.Hologram`.
            See :attr:`cameraslm`.
        null_region : array_like OR None
            Array of shape :attr:`shape`. Where ``True``, sets the background to zero
            instead of ``nan``. If ``None``, has no effect.
        null_region_radius_frac : float OR None
            Helper parameter to set the ``null_region`` to zero for Fourier space radius fractions above
            ``null_region_radius_frac``. This is useful to prevent power being deflected
            to very high orders, which are unlikely to be properly represented in
            practice on a physical SLM.
        target_ij_roi : (int, int) OR None
            See :attr:`target_ij_roi`. When given, ``target_ij`` is a sub-image
            of the camera frame anchored at this ``(y, x)`` camera pixel.
        **kwargs
            Passed to :meth:`Hologram.__init__`.
        """
        # Use the Hologram constructor to initialize self.target with proper shape,
        # pass other arguments (esp. slm_shape).
        self.cameraslm = cameraslm
        if self.cameraslm is not None:
            # Determine camera size in SLM-space.
            try:
                amp = self.cameraslm.slm._get_source_amplitude()
                slm_shape = self.cameraslm.slm.shape
            except Exception:
                # See if an SLM was passed.
                try:
                    amp = self.cameraslm._get_source_amplitude()
                    slm_shape = self.cameraslm.shape

                    # We don't have access to all the calibration stuff, so don't
                    # confuse the rest of the init/etc.
                    self.cameraslm = None
                except Exception:
                    raise ValueError("Expected a CameraSLM or SLM to be passed to cameraslm.")

        else:
            amp = kwargs.pop("amp", None)
            slm_shape = None

        if not "slm_shape" in kwargs:
            kwargs["slm_shape"] = slm_shape

        super().__init__(target=shape, amp=amp, **kwargs)

        self._updated_slm = False
        self.img_ij = None
        self.img_knm = None
        self.target_ij_roi = None       
        if target_ij is None:
            self.target_ij = None
        else:
            self.target_ij = target_ij.astype(self.dtype)

        if self.cameraslm is not None and "fourier" in self.cameraslm.calibrations:
            # Generate a list of the corners of the camera, for plotting.
            cam_shape = self.cameraslm.cam.shape

            ll = [0, 0]
            lr = [cam_shape[1] - 1, 0]
            ur = [cam_shape[1] - 1, cam_shape[0] - 1]
            ul = [0, cam_shape[0] - 1]

            points_ij = toolbox.format_2vectors(np.vstack((ll, lr, ur, ul, ll)).T)
            points_kxy = self.cameraslm.ijcam_to_kxyslm(points_ij)
            self._cam_points = toolbox.convert_vector(
                points_kxy,
                from_units="kxy",
                to_units="knm",
                hardware=self.cameraslm.slm,
                shape=self.shape
            )

            # Transform the target, if it is provided.
            if target_ij is not None:
                self.set_target(
                    target_ij,
                    null_region,
                    null_region_radius_frac,
                    reset_weights=True,
                    roi=target_ij_roi,
                )

        else:
            self._cam_points = None

            # Without a Fourier calibration the set_target() above never
            # runs, so a target_ij_roi would be dropped on the floor while
            # target_ij stays a sub-image -- silently leaving the two
            # inconsistent.
            if target_ij_roi is not None:
                raise ValueError(
                    "target_ij_roi requires a cameraslm with a Fourier calibration, "
                    "which is what interprets the sub-image's position."
                )

    # Image transformation helper functions.
    def _validate_roi(self, roi, src_shape):
        """
        Normalize ``roi`` to ``(int, int)`` or ``None``, requiring that the
        sub-image lies fully inside the camera frame. A sub-image that hangs
        off the edge has samples no camera frame could supply, and would
        silently mis-slice :attr:`img_ij` in :meth:`_update_stats`.
        """
        if roi is None:
            return None

        (y0, x0) = (int(roi[0]), int(roi[1]))
        (h, w) = (int(src_shape[0]), int(src_shape[1]))
        (ch, cw) = (int(self.cameraslm.cam.shape[0]),
                    int(self.cameraslm.cam.shape[1]))

        if y0 < 0 or x0 < 0 or y0 + h > ch or x0 + w > cw:
            raise ValueError(
                f"roi {(y0, x0)} with shape {(h, w)} does not fit inside the "
                f"{(ch, cw)} camera frame."
            )
        return (y0, x0)

    def _roi_window(self, img_ij):
        """
        The :attr:`target_ij_roi` window of a full camera frame, or the frame
        itself when no ROI is set. Every consumer that compares a measurement
        against :attr:`target_ij` must go through here, so the two stay on the
        same grid.

        The result is a view, not a copy; callers that upload it let
        :mod:`cupy` handle the compaction, which still moves only the window.
        """
        if self.target_ij_roi is None:
            return img_ij

        (y0, x0) = self.target_ij_roi
        (h, w) = np.shape(self.target_ij)
        return img_ij[y0:y0 + h, x0:x0 + w]

    def _ijcam_to_knmslm_resampler(self, src_shape, roi):
        """
        Return the (cached) composite ``"knm"`` -> ``"ij"`` transformation for
        this hologram's current geometry, as the augmented ``(2, 3)`` device
        matrix that :func:`cupyx.scipy.ndimage.affine_transform` accepts in
        place of a separate ``offset``. See :data:`_IJCAM_TO_KNMSLM_CACHE`.

        Handed a device array as ``offset``, ``affine_transform`` converts it
        elementwise with ``float()``, synchronizing once per element on every
        call; folding the offset into the matrix keeps the call entirely
        on-device for a bit-identical result.

        ``roi`` is validated here rather than by the caller because this is the
        single point every resampler is built through. Note that validation
        runs on every call, cache hit or not: it depends on ``src_shape``,
        which the transformation does not.

        Returns
        -------
        matrix : cupy.ndarray
            The augmented ``(2, 3)`` transformation.
        fresh : bool
            Whether this call built the entry rather than reusing a cached one.
            Lets the caller run once-per-geometry validation without paying for
            it every call.
        """
        slm = self.cameraslm.slm
        affine = self.cameraslm.fourier_affine
        roi = self._validate_roi(roi, src_shape)
        roi_key = (0, 0) if roi is None else roi

        # Everything the composite transformation is derived from. `order` and
        # `src_shape` are absent deliberately: the geometry does not depend on
        # either, so the resampling and measurement paths share one entry.
        key = (
            tuple(np.ravel(self.shape).tolist()),
            tuple(np.ravel(affine.M).tolist()),
            tuple(np.ravel(affine.b).tolist()),
            tuple(np.ravel(slm.pitch).tolist()),
            tuple(np.ravel(slm.shape).tolist()),
            roi_key,
        )

        matrix = _IJCAM_TO_KNMSLM_CACHE.get(key)
        if matrix is not None:
            return (matrix, False)

        # First transformation. FUTURE: make convert_basis to output a matrix
        # like here?
        conversion = (
            toolbox.convert_vector((1, 1), "knm", "kxy", hardware=slm,
                                   shape=self.shape) -
            toolbox.convert_vector((0, 0), "knm", "kxy", hardware=slm,
                                   shape=self.shape)
        )
        M1 = np.diag(np.squeeze(conversion))
        b1 = np.matmul(M1,
                       -toolbox.format_2vectors(np.flip(np.squeeze(self.shape))
                                                / 2))

        # Composite transformation (along with xy -> yx).
        M_np = np.flip(np.flip(np.matmul(affine.M, M1), axis=0), axis=1)
        b_np = np.flip(np.squeeze(np.matmul(affine.M, b1) + affine.b))

        if not (np.all(np.isfinite(M_np)) and np.all(np.isfinite(b_np))):
            raise RuntimeError(
                f"ijcam_to_knmslm produced a non-finite transformation (M={M_np}, b={b_np}). "
                "Check the Fourier calibration and that cameraslm.slm exposes a usable "
                "pitch and shape."
            )

        # An ROI shifts the origin of the source array: the sample at ``img[0,
        # 0]`` is the camera pixel at ``roi``, so the affine's ij output must
        # be rebased onto it.
        b_roi = b_np - np.asarray(roi_key, dtype=float)

        matrix = _IJCAM_TO_KNMSLM_CACHE.put(
            key, cp.array(np.hstack([M_np, b_roi.reshape(2, 1)]))
        )
        return (matrix, True)

    def ijcam_to_knmslm(self, img, out=None, blur_ij=None, order=3, roi=None):
        """
        Convert an image in the camera domain to computational SLM k-space using, in part, the
        affine transformation stored in a cameraslm's Fourier calibration.

        Note
        ~~~~
        This includes two transformations:

        - The affine transformation ``"ij"`` -> ``"kxy"`` (camera pixels to normalized k-space).
        - The scaling ``"kxy"`` -> ``"knm"`` (normalized k-space to computational k-space pixels).

        Parameters
        ----------
        img : numpy.ndarray OR cupy.ndarray
            Image to transform. This should be the same shape as images
            returned by the camera, unless ``roi`` is given (see below).
        out : numpy.ndarray OR cupy.ndarray OR None
            If ``out`` is not ``None``, this array will be used to write the memory in-place.
        blur_ij : int OR None
            Applies a ``blur_ij`` pixel-width Gaussian blur to ``img``.
            If ``None``, defaults to the ``"blur_ij"`` flag if present; otherwise zero.
            With ``roi``, the blur is applied within the sub-image.
        order : int
            Order of interpolation used for transformation. Defaults to 3 (cubic).
        roi : (int, int) OR None
            Region of interest, as the ``(y, x)`` camera pixel that ``img[0,
            0]`` corresponds to. When given, ``img`` is a *sub-image* of the
            camera frame rather than a full frame, and everything outside it is
            undefined (as ``numpy.nan`` padding would be). Only the sub-image
            is uploaded to the GPU, which is much cheaper than embedding it in
            a camera-sized canvas. If ``None``, ``img`` covers the full camera
            frame.

            Bounds are tested against the sub-image, so an output pixel whose
            source coordinate falls in the outer half-pixel rim of the ROI is
            undefined here while a full-frame canvas would have rounded it
            inward. Size the ROI with a pixel of margin around the signal and
            the difference does not arise.

            At ``order=0`` -- what :meth:`set_target` uses -- the result is
            otherwise identical to transforming the same sub-image embedded in
            a full frame. Above ``order=0`` it is identical only to within the
            spline prefilter, which is an IIR recursion over the whole input:
            cropping perturbs its coefficients everywhere, not just at the ROI
            edge. The perturbation is ~1e-4 of peak in intensity, rising to a
            few parts in a thousand once :meth:`measure` takes the square root,
            concentrated in the dimmest pixels. 

        Returns
        -------
        numpy.ndarray OR cupy.ndarray
            Image transformed into ``"knm"`` space.
        """
        if self.cameraslm is None:
            raise RuntimeError("Cannot use ijcam_to_knmslm without the calibrations in a cameraslm.")
        if not "fourier" in self.cameraslm.calibrations:
            raise RuntimeError("ijcam_to_knmslm requires a Fourier calibration.")

        # See if the user wants to blur.
        if blur_ij is None:
            if "blur_ij" in self.flags:
                blur_ij = self.flags["blur_ij"]
            else:
                blur_ij = 0

        # FUTURE: use cp_gaussian_filter (faster?); was having trouble with cp_gaussian_filter.
        if blur_ij > 0:
            # scipy's filter is host-only.
            img = sp_gaussian_filter(as_numpy(img), (blur_ij, blur_ij), truncate=2)

        # The composite transformation is pure geometry, so it is derived once and
        # cached across the repeated calls made by set_target() and measure().
        (matrix, fresh) = self._ijcam_to_knmslm_resampler(np.shape(img), roi)

        cp_img = cp.array(img, dtype=self.dtype)
        cp.abs(cp_img, out=cp_img)

        # Perform affine. `matrix` is augmented, carrying the offset in its
        # last column; passing a separate `offset=` would synchronize. See
        # _ijcam_to_knmslm_resampler.
        target = cp_affine_transform(
            input=cp_img,
            matrix=matrix,
            output_shape=self.shape,
            order=order,
            output=out,
            mode="constant",
            cval=np.nan,
        )

        # Filter the image. FUTURE: fix.
        # target = cp_gaussian_filter1d(target, blur, axis=0, output=target, truncate=2)
        # target = cp_gaussian_filter1d(target, blur, axis=1, output=target, truncate=2)

        target = cp.abs(target, out=target)
        norm = Hologram._norm(target)

        # Only checked on a fresh geometry. A zero norm here means the camera
        # basis does not overlap knm space at all -- a property of the
        # transformation, which is fixed for the life of a cache entry, not of
        # the image. Testing it on every call would cost a device
        # synchronization to read `norm` back, which dominates this method in
        # the feedback loop.
        if fresh and float(norm) == 0:
            raise ValueError(
                "No power in hologram. Maybe target_ij is out of range of knm space? "
                "Check transformations."
            )

        target *= 1 / norm

        return target

    # Measurement.
    def _update_slm(self, force=False, cleanup_images=True):
        """
        Method to update the SLM with the current phase pattern.
        This is separate from :meth:`measure()`
        """
        if not self._updated_slm or force:   # If we have not already updated the SLM.
            # Parse the current feedback and stats to see if an update is needed.
            should_update = False
            feedback = self.flags.get("feedback", "")

            if "experimental" in feedback or "external" in feedback:
                should_update = True

            for group in self.flags.get("stat_groups", []):
                if "experimental" in group or "external" in group:
                    should_update = True

            # Then actually update the SLM.
            if should_update and self.cameraslm is not None:
                self.cameraslm.slm.set_phase(self.get_phase(include_propagation=True), settle=True)
                self._updated_slm = True

                # Erase images from the past loop.
                if cleanup_images:
                    self.img_ij = None
                    self.img_knm = None

    def _nearfield_extract(self):
        """Invalidate the projection flag; the recomputed phase is not yet on the SLM."""
        super()._nearfield_extract()
        self._updated_slm = False

    def measure(self, basis="ij"):
        """
        Method to request a measurement to occur. If :attr:`img_ij` is ``None``,
        then a new image will be grabbed from the camera (this is done automatically in
        algorithms).

        Parameters
        ----------
        basis : str
            The cached image to be sure to fill with new data.
            Can be ``"ij"`` or ``"knm"``.

            - If ``"knm"``, then :attr:`img_ij` and :attr:`img_knm` are filled.
            - If ``"ij"``, then :attr:`img_ij` is filled, and :attr:`img_knm` is ignored.

            This is useful to avoid (expensive) transformation from the ``"ij"`` to the
            ``"knm"`` basis if :attr:`img_knm` is not needed.
        """
        if self.cameraslm is None and self.img_ij is None:
            raise RuntimeError(
                "measure() requires a cameraslm to grab an image from; "
                "construct this hologram with cameraslm=... or set img_ij directly."
            )

        # Make sure the SLM is updated before measurement (usually, the SLM should already be updated.
        self._update_slm()

        if self.img_ij is None and (basis == "knm" or basis == "ij"):
            # Measure the result.
            self.cameraslm.cam.flush()
            # get=False so that a simulated camera's frame never crosses the bus.
            raw_img = self.cameraslm.cam.get_image(get=False)
            if is_gpu_array(raw_img):
                self.img_ij = cp.asarray(raw_img, dtype=self.dtype)
            else:
                self.img_ij = np.array(
                    raw_img, copy=(False if np.__version__[0] == '1' else None), dtype=self.dtype
                )

            try:
                if basis == "knm":  # Compute the knm basis image.
                    # Window by the ROI, when there is one: the rest of the frame
                    # is outside the target and would only be uploaded to be
                    # discarded by the transform.
                    self.img_knm = self.ijcam_to_knmslm(
                        self._roi_window(self.img_ij),
                        out=self.img_knm,
                        roi=self.target_ij_roi,
                    )
                    cp.sqrt(self.img_knm, out=self.img_knm)
                else:  # The old image is outdated, erase it. FUTURE: memory concerns?
                    self.img_knm = None

                xp_ij = get_array_module(self.img_ij)
                self.img_ij = xp_ij.sqrt(self.img_ij)
            except BaseException:
                # Else the cache holds intensity where every reader expects amplitude.
                self.img_ij = self.img_knm = None
                raise
        elif basis == "knm":
            if self.img_knm is None:
                # Square the window, not the frame; img_ij is amplitude by this
                # point.
                xp_ij = get_array_module(self.img_ij)
                self.img_knm = self.ijcam_to_knmslm(
                    xp_ij.square(self._roi_window(self.img_ij)),
                    out=self.img_knm,
                    roi=self.target_ij_roi,
                )
                cp.sqrt(self.img_knm, out=self.img_knm)
        elif basis == "ij":
            pass
        else:
            raise ValueError(f"Unrecognized measurement basis '{basis}'. Options are 'ij' or 'knm'")

    # Target update.
    def set_target(
        self,
        new_target_ij,
        null_region=None,
        null_region_radius_frac=None,
        reset_weights=False,
        roi=None,
    ):
        r"""
        Change the target to something new. This method handles cleaning and normalization.

        Parameters
        ----------
        new_target_ij : array_like OR None
            New :attr:`target_ij` to optimize towards *in the camera basis*.
            Should be of the same shape as the camera, unless ``roi`` is given.
            Also updates :attr:`target` using the stored Fourier calibration.
        null_region : array_like OR None
            Array of shape :attr:`shape`.
            Where this array is ``True``, ``nan`` entries in the :attr:`target` are replaced with zeros.
            If ``None``, has no effect.
        null_region_radius_frac : float OR None
            Helper parameter to set the ``null_region`` to zero for Fourier space radius fractions above
            ``null_region_radius_frac``. This is useful to prevent power being deflected
            to very high orders, which are unlikely to be properly represented
            on a physical SLM. If ``None``, defaults to :math:`\sqrt{2}`
            (circumscribing the square farfield in fractional units)
            and there is no null region.
        reset_weights : bool
            Whether to update the :attr:`weights` to this new :attr:`target`.
        roi : (int, int) OR None
            Region of interest, as the ``(y, x)`` camera pixel that
            ``new_target_ij[0, 0]`` corresponds to. When given,
            ``new_target_ij`` is a sub-image of the camera frame and everything
            outside it is undefined; see :meth:`ijcam_to_knmslm`. Must lie
            fully inside the camera frame. Stored as :attr:`target_ij_roi`.
        """
        self.target_ij = new_target_ij.astype(self.dtype)
        # Normalize once here and pass the result down, rather than validating
        # in both places. ijcam_to_knmslm validates too (see
        # _ijcam_to_knmslm_resampler), so a bad roi raises either way -- this
        # just avoids normalizing it twice.
        self.target_ij_roi = self._validate_roi(roi, np.shape(new_target_ij))
        # Transformation order of zero to prevent nan-blurring in MRAF cases.
        self.ijcam_to_knmslm(
            new_target_ij, out=self.target, order=0, roi=self.target_ij_roi
        )

        # Set the null region.
        undefined = cp.isnan(self.target)

        # Start from the user-provided null mask, if any.
        if null_region is not None:
            null_region = cp.asarray(null_region, dtype=bool)

        if null_region_radius_frac is None:
            null_region_radius_frac = np.sqrt(2)

        if null_region_radius_frac < np.sqrt(2):
            # Build up the null region pattern if we have not already done the transform above.
            if null_region is None:
                null_region = cp.zeros(self.shape, dtype=bool)

            # Make a circle, outside of which the null_region is active.
            xl = cp.linspace(-1, 1, null_region.shape[1])
            yl = cp.linspace(-1, 1, null_region.shape[0])
            (xg, yg) = cp.meshgrid(xl, yl)
            mask = cp.square(xg) + cp.square(yg) > null_region_radius_frac**2
            null_region[mask] = True

        if not (null_region is None):
            self.target[cp.logical_and(undefined, null_region)] = 0

        if reset_weights:
            self.reset_weights()

    def refine_offset(self, img, basis="kxy"):
        """
        **(NotImplemented)**
        Hones the position of the produced image to the desired target image to compensate for
        Fourier calibration imperfections. Works either by moving the desired camera
        target to align where the image ended up (``basis="ij"``) or by moving
        the :math:`k`-space image to target the desired camera target
        (``basis="knm"``/``basis="kxy"``). This should be run at the user's request
        between :meth:`optimize` iterations.

        Parameters
        ----------
        img : numpy.ndarray
            Image measured by the camera.
        basis : str
            The correction can be in any of the following bases:
            - ``"ij"`` changes the pixel that the spot is expected at,
            - ``"kxy"`` or ``"knm"`` changes the k-vector which the SLM targets.
            Defaults to ``"kxy"`` if ``None``.

        Returns
        -------
        numpy.ndarray
            Euclidean pixel error in the ``"ij"`` basis for each spot.
        """
        # Probably local autocorrelation algorithm.

        raise NotImplementedError()

    # Weighting and stats.
    def _update_weights(self):
        """
        Change :attr:`weights` to optimize towards the :attr:`target` using feedback from
        :attr:`amp_ff`, the computed farfield amplitude.
        """
        feedback = self.flags["feedback"]

        if feedback == "computational":
            self._update_weights_generic(self.weights, self.amp_ff, self.target)
        elif feedback == "experimental":
            self.measure("knm")  # Make sure data is there.
            self._update_weights_generic(self.weights, self.img_knm, self.target)

    def _calculate_stats_experimental(self, stats, stat_groups=None):
        """
        Wrapped by :meth:`FeedbackHologram._update_stats()`.
        """
        if stat_groups is None: stat_groups = []
        if "experimental_knm" in stat_groups:
            self.measure("knm")  # Make sure data is there.

            stats["experimental_knm"] = self._calculate_stats(
                self.img_knm,
                self.target,
                efficiency_compensation=True,
                raw="raw_stats" in self.flags and self.flags["raw_stats"],
            )
        if "experimental_ij" in stat_groups or "experimental" in stat_groups:
            if self.target_ij is None:
                raise ValueError(
                    "Stat groups 'experimental' and 'experimental_ij' need a "
                    "camera-referenced target; this hologram has none. "
                    "Use 'experimental_knm' instead."
                )
            self.measure("ij")  # Make sure data is there.

            # When the target was supplied as a sub-image, compare against the
            # matching window of the measurement rather than the full frame.
            # Everything outside the ROI is undefined, so it never contributed
            # to these statistics anyway.
            stats["experimental_ij"] = self._calculate_stats(
                self._roi_window(self.img_ij),
                self.target_ij,
                xp=np,
                efficiency_compensation=True,
                raw="raw_stats" in self.flags and self.flags["raw_stats"],
            )

    def _update_stats(self, stat_groups=None):
        """
        Calculate statistics corresponding to the desired ``stat_groups``.

        Parameters
        ----------
        stat_groups : list of str
            Which groups or types of statistics to analyze.
        """
        stats = {}

        self._calculate_stats_computational(stats, stat_groups)
        self._calculate_stats_experimental(stats, stat_groups)

        self._update_stats_dictionary(stats)
